[tox]
envlist = py312, py310

skipsdist = True

[testenv]
deps =
    -rrequirements.txt
    -rtest-requirements.txt
commands =
    flake8 --extend-exclude=venv,migrations --ignore=E402
    bandit -n5 -x "./venv/*,./tests/*,./.tox/*,./dev-tools/*" -r . -ll
    pytest -v --cov=. --cov-config=.coveragerc-ci --cov-report html \
           --cov-report term -p no:warnings -n {posargs:2} tests/api/
    find ./instance -name 'test_*' -delete
allowlist_externals = find
